site_name: BonoboNET

theme: cinder


nav:
    - index.md
    - rules.md
    - servers.md
    - Usage:
        - botty.md
    - Blog:
        - OpenBNET: blog/3.md
        - Services migrated: blog/2.md
        - New site: blog/1.md
    - Network:
        - join.md
        - Configuration:
            - peering.md
            - configuring.md
            - motd.md
            - linking.md
        - links.md
        - OpenBNET: openbnet.md
    - culture.md