site_name: BonoboNET
site_url: https://bnet.eu.org/
#site_url: http:///projects/bonobonet/

theme:
  name: cinder

nav:
  - index.md
  - rules.md
  - servers.md
  - Usage:
      - botty.md
  - blog.md
  - Network:
      - join.md
      - Configuration:
          - network/peering.md
          - network/credentials.md
          - network/daemon.md
          - network/monitoring.md
          - network/motd.md
          - network/linking.md
      - links.md
      - OpenBNET: openbnet.md
  - culture.md

plugins:
  - blogging:
      features:
        tags: {}
      locale: en
      meta_time_format: '%Y-%m-%dT%H:%M:%S%z'
      dirs: # The directories to be included
        - blog

  - search
  - git-revision-date
  - print-site

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details

  - pymdownx.tasklist:
      custom_checkbox: true
